window.DECK = {
  "course": "Android-разработка",
  "lecture": 1,
  "lectureId": "01",
  "slug": "01-vvedenie",
  "title": "Введение в Android. Инструменты. Git и GitHub",
  "block": "Старт и инструменты",
  "teacher": "Сучёв Николай Евгеньевич",
  "teacherMeta": "Android-разработчик · Т-Банк · команда Вовлечение",
  "hub": "../../index.html",
  "photo": "../../assets/teacher.jpg",
  "slides": [
    {
      "type": "title",
      "title": "Android-разработка",
      "subtitle": "Лекция 1. Введение в Android. Инструменты. Git и GitHub",
      "badge": "",
      "body": "- Курс из 15 лекций\n- Пара 1,5 часа: теория + практика\n- Работаем с репозиторием [FinanceApp](https://github.com/kolxz2/FinanceApp)\n- Преподаватель: Сучёв Николай Евгеньевич",
      "notes": "Поприветствовать группу: «Меня зовут Николай Сучёв, я Android-разработчик в Т-Банке». Сказать, что сегодня не пишем сложный код: ставим инструменты, понимаем, из чего состоит приложение, и учимся сдавать работу через GitHub. Без Git с этой лекции ДЗ не принимается.",
      "kicker": "01 / 15",
      "photo": true
    },
    {
      "type": "teacher",
      "title": "Кто ведёт курс",
      "subtitle": "Сучёв Николай Евгеньевич",
      "badge": "",
      "body": "- Android-разработчик, **Т-Банк**\n- Команда **Вовлечение**\n- Middle, **2 года** коммерческого опыта",
      "notes": "1–2 минуты, не больше. Представиться полностью: Николай Евгеньевич Сучёв. Работаю Android-разработчиком в Т-Банке, команда Вовлечение — продуктовые фичи, которые возвращают человека в приложение и помогают им пользоваться. Грейд middle, два года в проде: не гуру с 15-летним стажем, а человек, который недавно проходил этот путь и до сих пор каждый день открывает Studio, Logcat и GitHub. Спросить, кто уже пробовал Android / Kotlin / Git — поднять руки. Пообещать: курс про фундамент, который используется в индустрии, а не про «магическую кнопку Run».",
      "kicker": "",
      "photo": true
    },
    {
      "type": "content",
      "title": "Что вы умеете к концу пары",
      "subtitle": "",
      "badge": "",
      "body": "- Понимаете, что такое Android-приложение (APK, манифест, компоненты)\n- Понимаете роль JDK / JVM и экосистему Android\n- Установлены Android Studio, SDK и эмулятор (или проверены)\n- Клонируете [FinanceApp](https://github.com/kolxz2/FinanceApp) и запускаете проект\n- Делаете commit, push и открываете первый Pull Request",
      "notes": "Это критерий успеха пары. К концу занятия у каждого открыт первый Pull Request в FinanceApp.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "О курсе",
      "subtitle": "Один проект развивается на протяжении 15 лекций",
      "badge": "",
      "body": "- Приложение для ведения операций\n- Теория сразу закрепляется практикой\n- Каждая лекция добавляет новую возможность\n- Весь код хранится в одном репозитории",
      "outcome": "Понимаете, какое приложение создаём и как будет устроена работа на курсе.",
      "notes": "Сначала договоримся о правилах. Потом техника. Иначе половина группы не поймёт, зачем Git с первой пары.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "15 лекций — одна дорога",
      "subtitle": "",
      "badge": "",
      "body": "| Блок | Лекции | Тема |\n| Старт и инструменты | 1 | Android, Android Studio, Git / GitHub |\n| Язык | 2–4 | Kotlin |\n| Основы Android | 5–8 | Activity, UI, списки, Fragment / Navigation |\n| Компоненты и сеть | 9–11 | Service / BR / CP, сеть + JSON, корутины + Flow |\n| Данные | 12 | SharedPreferences, DataStore, Room, файлы |\n| Архитектура | 13–14 | MVVM / SOLID / Clean, паттерны, DI / Hilt |\n| Финал | 15 | Сборка приложения, самопроверка, заключение |",
      "notes": "Не надо запоминать все слова. Важно: мы идём от языка → экраны → сеть → данные → архитектура. Сегодня — фундамент: среда и Git.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Приложение для ведения операций",
      "subtitle": "",
      "badge": "",
      "body": "- В течение курса развиваем [FinanceApp](https://github.com/kolxz2/FinanceApp)\n- Пользователь видит список операций и открывает подробную информацию\n- Новые операции загружаются из сети и сохраняются локально\n- По мере изучения курса добавляем навигацию, хранение данных и архитектуру\n- Домашние работы сдаём веткой `homework/...` и Pull Request в `master`",
      "notes": "Это сквозной учебный проект. Под операцией понимаем запись с суммой, категорией, датой и описанием. На первых лекциях работаем с простыми данными, затем подключаем экран деталей, сеть, локальное хранение и архитектуру.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Git с этой лекции обязателен для всех ДЗ",
      "subtitle": "",
      "badge": "",
      "body": "- Нет GitHub — нет сдачи\n- Нет ветки и PR — работа не считается сданной\n- Преподаватель смотрит код в Pull Request, не в мессенджере\n- Вопросы по ДЗ тоже лучше писать в PR: контекст рядом с кодом",
      "notes": "Это не бюрократия. В Т-Банке, как и почти везде в индустрии, код живёт в Git: ветка, PR, ревью. Курс с первой пары повторяет этот процесс.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Что такое Android",
      "subtitle": "Платформа, на которой будет работать наше приложение",
      "badge": "",
      "body": "- Как Android превратился в открытую платформу\n- Что находится внутри экосистемы\n- Зачем Android нужны Kotlin, JDK и ART\n- Как версия системы связана с API Level",
      "outcome": "Видите Android как систему взаимосвязанных технологий, а не только экран телефона.",
      "notes": "Короткий исторический блок, затем — из чего состоит приложение. Без этого Studio выглядит «магической кнопкой Run».",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Android — это не только телефоны",
      "subtitle": "",
      "badge": "",
      "body": "- Операционная система на ядре Linux\n- Платформа для приложений: телефон, планшет, часы, TV, авто\n- На курсе фокус: **мобильное приложение** (телефон / эмулятор)\n- Приложения пишут в основном на **Kotlin** (раньше — Java)",
      "image": "../../assets/concepts/android-devices.png",
      "imageKind": "visual",
      "imageAlt": "Телефон, планшет, складной экран, часы, телевизор и автомобиль с Android",
      "imageCaption": "Одна платформа работает на устройствах с разными формами экрана",
      "notes": "Android — экосистема Google. Мы учим прикладную разработку под телефоны. Wear / TV / Auto — те же идеи, другой UI.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "От стартапа до открытой платформы",
      "subtitle": "",
      "badge": "",
      "body": "- **2003** — основана компания Android Inc.\n- **2005** — Google приобретает Android Inc.\n- **5 ноября 2007** — объявлены Android и Open Handset Alliance\n- **12 ноября 2007** — разработчики получают раннюю версию Android SDK\n- В SDK уже были эмулятор, отладчик и инструменты профилирования\n- Google запустила Android Developer Challenge с призовым фондом **$10 млн**",
      "notes": "История раннего SDK: https://android-developers.googleblog.com/2007/11/posted-by-jason-chen-android-advocate.html.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Android 1.0 и первый телефон",
      "subtitle": "",
      "badge": "",
      "body": "- **23 сентября 2008** — выпущен Android 1.0 SDK\n- Первым коммерческим устройством стал **T-Mobile G1**, также известный как HTC Dream\n- **21 октября 2008** Google и партнёры открыли исходный код Android\n- **22 октября 2008** G1 поступил в продажу вместе с Android Market\n- Пользователи могли скачивать приложения, ставить оценки и писать отзывы",
      "notes": "Источники: https://android-developers.googleblog.com/2008/09/announcing-android-10-sdk-release-1.html и https://android-developers.googleblog.com/2008/10/android-is-now-open-source.html.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Kotlin и Jetpack меняют разработку",
      "subtitle": "",
      "badge": "",
      "body": "- **2017** — Google объявляет официальную поддержку Kotlin для Android\n- Android Studio 3.0 получает встроенную поддержку Kotlin\n- **2018** — представлен Android Jetpack и пространство имён `androidx.*`\n- **2019** — Android-разработка становится Kotlin-first\n- Документация, примеры и новые библиотеки сначала проектируются для Kotlin\n- Jetpack Compose становится Kotlin-only инструментом для создания UI",
      "notes": "Источники: https://android-developers.googleblog.com/2017/05/android-announces-support-for-kotlin.html и https://android-developers.googleblog.com/2022/08/celebrating-5-years-of-kotlin-on-android.html.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Android OS",
      "subtitle": "Операционная система на устройстве",
      "badge": "",
      "body": "- Управляет процессами, памятью, файлами и оборудованием\n- Предоставляет приложениям системные API\n- Изолирует приложения друг от друга\n- Запускает код через Android Runtime\n- Версия системы определяет доступный API Level",
      "image": "../../assets/ecosystem/android-os.jpg",
      "imageAlt": "Логотип Android",
      "imageCaption": "Android OS работает на телефонах и других типах устройств",
      "notes": "На этом уровне находятся Linux kernel, системные службы, Android Runtime и framework API.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Google Play",
      "subtitle": "Канал распространения приложений",
      "badge": "",
      "body": "- Пользователь находит и устанавливает приложения\n- Разработчик публикует сборки через Play Console\n- Магазин доставляет обновления\n- Перед публикацией приложение подписывают цифровым ключом\n- Android допускает другие магазины и установку APK напрямую",
      "image": "../../assets/ecosystem/google-play.png",
      "imageAlt": "Логотип Google Play",
      "imageCaption": "Google Play — основной, но не единственный магазин Android",
      "notes": "На курсе публикация в Google Play не требуется. Важно понимать разницу между сборкой и распространением.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Android SDK",
      "subtitle": "API и инструменты для сборки приложения",
      "badge": "",
      "body": "- Содержит API для выбранных версий Android\n- Включает build-tools, platform-tools и эмулятор\n- Команда `adb` связывает компьютер с устройством\n- `sdkmanager` устанавливает пакеты SDK\n- Проект задаёт `minSdk`, `compileSdk` и `targetSdk`",
      "image": "../../assets/ecosystem/android-sdk.svg",
      "imageAlt": "Значок Android SDK",
      "imageCaption": "SDK превращает код и ресурсы в устанавливаемое приложение",
      "notes": "SDK — набор платформ, API и командных инструментов. Android Studio управляет ими через SDK Manager.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Android Studio",
      "subtitle": "Официальная IDE для Android-разработки",
      "badge": "",
      "body": "- Редактор Kotlin, Java и XML\n- Создание проекта и управление Gradle\n- Запуск на эмуляторе или устройстве\n- Logcat, debugger, profiler и инспекции кода\n- Основана на платформе IntelliJ IDEA",
      "image": "../../assets/ecosystem/android-studio.png",
      "imageAlt": "Логотип Android Studio",
      "imageCaption": "В Android Studio пишут, собирают, запускают и отлаживают приложение",
      "notes": "Официальная страница: https://developer.android.com/studio.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Android Jetpack",
      "subtitle": "Библиотеки поверх Android framework",
      "badge": "",
      "body": "- Готовые компоненты для типовых задач\n- ViewModel хранит состояние экрана\n- Navigation управляет переходами\n- Room работает с локальной базой данных\n- WorkManager запускает фоновую работу\n- Библиотеки публикуются в пакетах `androidx.*`",
      "image": "../../assets/ecosystem/jetpack.svg",
      "imageAlt": "Иллюстрация Android Jetpack",
      "imageCaption": "Jetpack сокращает количество инфраструктурного кода",
      "notes": "Jetpack представлен в 2018 году: https://android-developers.googleblog.com/2018/05/use-android-jetpack-to-accelerate-your.html.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Kotlin",
      "subtitle": "Основной язык курса",
      "badge": "",
      "body": "- Статически типизированный язык от JetBrains\n- Полностью взаимодействует с Java-кодом\n- Поддерживает null safety\n- Корутины упрощают асинхронную работу\n- Google поддерживает Kotlin для Android с 2017 года\n- С 2019 года Android развивается по принципу Kotlin-first",
      "image": "../../assets/ecosystem/kotlin.png",
      "imageAlt": "Логотип Kotlin",
      "imageCaption": "Kotlin используется во всех практических заданиях курса",
      "notes": "Материалы: https://kotlinlang.org/docs/kotlin-brand-assets.html.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Зачем здесь JDK и JVM",
      "subtitle": "",
      "badge": "",
      "body": "- **JDK** (Java Development Kit) — компилятор и инструменты для JVM-языков\n- **JVM** (Java Virtual Machine) — виртуальная машина, которая исполняет байткод\n- Kotlin компилируется в байткод, совместимый с Java\n- Android Studio ставит нужный JDK сама — отдельно «искать Java» обычно не нужно\n- На устройстве код выполняется уже не классической JVM, а в среде Android (ART)",
      "notes": "Студенты часто путают «Java как язык» и «Java как платформа». Мы пишем на Kotlin, но стоим на JVM-стеке. ART (Android Runtime) — преемник Dalvik, исполняет приложение на телефоне.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "На курсе язык — Kotlin",
      "subtitle": "",
      "badge": "",
      "body": "- Google рекомендует Kotlin для нового Android-кода\n- Лекции 2–4 — только язык, почти без UI\n- Java знать полезно (старые проекты), писать на курсе не будем\n- Если умеете Java — Kotlin освоите быстрее, но это другой синтаксис",
      "notes": "Не начинайте гуглить «Android tutorial Java 2015». Стек курса: Kotlin, View Binding, Navigation, Retrofit, корутины, Room, Hilt.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Версия Android ≠ версия приложения",
      "subtitle": "",
      "badge": "",
      "body": "- У ОС есть **API Level** (например, 34 = Android 14)\n- **minSdk** — минимальная версия, на которой приложение запустится\n- **targetSdk** — версия, под которую вы собирали и тестировали\n- Эмулятор должен быть ≥ minSdk\n- На курсе конкретные числа скажет шаблон проекта",
      "notes": "Не ставьте minSdk слишком высокий «на всякий случай» — отрежете старые телефоны. И слишком низкий — потеряете современные API. Для учёбы берём значение из шаблона.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Что такое Android-приложение",
      "subtitle": "Что именно собирает и запускает Android Studio",
      "badge": "",
      "body": "- Из чего состоит APK\n- Как манифест описывает приложение\n- Какие задачи решают Activity, Service и Receiver\n- Как система находит первый экран",
      "outcome": "Можете объяснить путь от исходного кода до запущенного экрана.",
      "notes": "Это обзор. Подробно Activity — лекция 5, остальные компоненты — лекция 9. Сегодня нужен словарь, не реализация.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "APK — это установочный пакет",
      "subtitle": "",
      "badge": "",
      "body": "- **APK** = Android Package\n- Похож на zip-архив: код, ресурсы (картинки, вёрстка), манифест\n- Studio собирает APK (или AAB для Play) кнопкой Run / Build\n- На эмулятор/телефон ставится именно пакет, не «папка с исходниками»\n- Исходники ≠ то, что видит пользователь",
      "notes": "AAB (Android App Bundle) — формат для Google Play. На курсе достаточно APK через Run. Не рассылайте друг другу исходники мессенджером — для этого Git.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "AndroidManifest.xml — паспорт приложения",
      "subtitle": "",
      "badge": "",
      "body": "- Обязательный файл каждого приложения\n- Объявляет: имя пакета, иконку, Activity, сервисы, разрешения\n- Система читает манифест **до** запуска кода\n- Не объявили экран в манифесте — система о нём не знает\n- На курсе править манифест начнём с лекции 5, сегодня — знать, что он есть\n\n```xml\n<manifest>\n  <application>\n    <activity android:name=\".MainActivity\" />\n  </application>\n</manifest>\n```",
      "notes": "Открыть в Studio файл `app/src/main/AndroidManifest.xml` на проекте-шаблоне, показать 20 секунд, не разбирать каждую строку.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Четыре типа компонентов Android",
      "subtitle": "",
      "badge": "",
      "body": "1. **Activity** — экран, с которым работает пользователь\n2. **Service** — работа без UI (музыка, загрузка)\n3. **BroadcastReceiver** — реакция на системные и свои события\n4. **ContentProvider** — доступ к данным (контакты, медиа) для других приложений",
      "notes": "Запомнить четыре имени. Activity увидим в шаблоне Hello World. Остальные — лекция 9. Не пытайтесь сегодня написать Service.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Activity — это экран",
      "subtitle": "",
      "badge": "",
      "body": "- Одно Activity ≈ один экран (упрощение, но на старте верное)\n- Пользователь видит UI: текст, кнопки, списки\n- Приложение может состоять из нескольких Activity\n- Позже заменим пачку Activity на Fragment + Navigation (лекция 8)\n- Hello World курса — одно Activity с текстом на экране",
      "image": "../../assets/concepts/activity-screen.png",
      "imageKind": "visual",
      "imageAlt": "Связь класса Activity с экраном приложения",
      "imageCaption": "На старте курса используем модель: одно Activity — один видимый экран",
      "notes": "«Упрощение» важно произнести. Иначе на 8-й лекции будет ощущение, что мы их обманули. Пока — один экран, один Activity.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Не вы запускаете Activity — система",
      "subtitle": "",
      "badge": "",
      "body": "1. Пользователь нажимает иконку\n2. Android читает манифест\n3. Система находит launcher Activity\n4. Создаётся процесс приложения\n5. Activity получает жизненный цикл и показывает экран",
      "layout": "roadmap",
      "notes": "У Kotlin есть `fun main()`, мы им воспользуемся на лекциях 2–4 в scratch/консоли. В приложении точка входа — компонент, объявленный в манифесте.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Инструменты",
      "subtitle": "Рабочее окружение Android-разработчика",
      "badge": "",
      "body": "- Установка Android Studio\n- Платформы и инструменты в SDK Manager\n- Виртуальное устройство в Device Manager\n- Проверка подключения через adb",
      "outcome": "Подготовлено окружение, на котором можно собрать и запустить приложение.",
      "notes": "Кто не поставил Studio заранее — ставим сейчас фоном, пока идёт обзор. Скачивание долгое: не ждать всех молча, идём дальше и возвращаемся к установке.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Установка Android Studio — порядок",
      "subtitle": "",
      "badge": "",
      "body": "1. Скачать установщик с developer.android.com/studio\n2. Next → принять лицензии SDK\n3. Standard-установка (не Custom, если не уверены)\n4. Дождаться загрузки SDK и системного образа эмулятора\n5. Первый запуск: не закрывать окно, пока не скачается SDK",
      "notes": "Типичная ошибка — убить установщик на 90%. Вторая — поставить Studio без образа эмулятора и удивиться, что нечего запускать.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "SDK — не «ещё одна программа», а набор платформ",
      "subtitle": "",
      "badge": "",
      "body": "- SDK Manager в Studio: Tools → SDK Manager\n- **SDK Platforms** — версии Android для компиляции и эмуляторов\n- **SDK Tools** — build-tools, emulator, platform-tools (`adb`)\n- `adb` — мост между компьютером и устройством (логи, установка APK)\n- Без SDK проект не соберётся, даже если Studio открывается",
      "image": "../../assets/ide/sdk-manager.png",
      "imageKind": "screenshot",
      "imageAlt": "Окно SDK Manager в Android Studio",
      "imageCaption": "Открыть: Tools → SDK Manager. Нужные пакеты отмечаются флажками",
      "notes": "Показать, где SDK Manager. Не ставить все платформы подряд — диск кончится. Нужны: одна свежая платформа + build-tools, которые просит Gradle.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Эмулятор — виртуальный телефон на ПК",
      "subtitle": "",
      "badge": "",
      "body": "- Device Manager: создать Virtual Device (AVD)\n- Рекомендация на курс: Pixel, x86_64, свежий системный образ **без** обязательного Play Store (легче и быстрее)\n- Первый запуск образа — несколько минут\n- Альтернатива: своё устройство + USB debugging\n- Эмулятор ест CPU и RAM — закройте лишние браузеры",
      "image": "../../assets/ide/device-manager.png",
      "imageKind": "screenshot",
      "imageAlt": "Окно Device Manager в Android Studio",
      "imageCaption": "Открыть: View → Tool Windows → Device Manager. Кнопка + создаёт AVD",
      "notes": "Если эмулятор чёрный экран / «waiting for device» — чаще виртуализация выключена в BIOS или конфликт Hyper-V. Не тратить на это всю пару: переключиться на телефон.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "practice",
      "title": "Практика. Проверяем, что среда живая",
      "subtitle": "",
      "badge": "Практика",
      "body": "Чеклист (галочка = готовы идти дальше):\n\n- [ ] Android Studio открывается\n- [ ] SDK Manager видит установленную платформу\n- [ ] Есть AVD или подключен телефон (`adb devices`)\n- [ ] Git установлен: в терминале `git --version`\n- [ ] Есть аккаунт GitHub",
      "image": "../../assets/ide/device-manager-open.png",
      "imageKind": "screenshot",
      "imageAlt": "Расположение Device Manager в Android Studio",
      "imageCaption": "Device Manager находится в правой панели инструментов IDE",
      "notes": "5 минут. Кто застрял на эмуляторе — не блокирует группу, фиксируем проблему, идём к Git. Studio можно доставить дома, Git — нет смысла откладывать.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Обзор Android Studio",
      "subtitle": "Где находятся основные инструменты IDE",
      "badge": "",
      "body": "- Project и структура модуля app\n- Build и задачи Gradle\n- Выбор устройства и кнопка Run\n- Logcat и сообщения приложения",
      "outcome": "Находите нужное окно IDE и понимаете, куда смотреть при ошибке.",
      "notes": "Не экскурсия по всем меню. Четыре вещи, без которых не проживёте неделю: дерево проекта, Gradle, кнопка Run, Logcat.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Окно Android Studio",
      "subtitle": "Основные области интерфейса",
      "badge": "",
      "body": "**1** Toolbar · **2** Navigation · **3** Editor · **4** Tool windows · **5** Открытое окно инструмента · **6** Status bar",
      "layout": "screenshot-focus",
      "image": "../../assets/ide/main-window-cropped.png",
      "imageKind": "screenshot",
      "imageAlt": "Основные области окна Android Studio",
      "imageCaption": "",
      "notes": "Вид «Android» группирует manifests / java / res. Вид «Project» нужен, когда ищем `build.gradle.kts` и `.gitignore`.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Где что лежит (модуль app)",
      "subtitle": "Project: View → Tool Windows → Project или Alt+1",
      "badge": "",
      "body": "- `app/src/main/java` или `kotlin` — исходный код\n- `app/src/main/res` — ресурсы приложения\n- `AndroidManifest.xml` — компоненты и разрешения\n- `app/build.gradle.kts` — настройки модуля и зависимости\n- Файлы Gradle в корне — настройка всего проекта\n- `gradle/` и `gradlew` — Gradle Wrapper",
      "layout": "screenshot-tall",
      "image": "../../assets/ide/project-view.png",
      "imageKind": "screenshot",
      "imageAlt": "Структура Android-проекта в окне Project",
      "imageCaption": "",
      "notes": "Wrapper важен: не ставим Gradle «как получится» вручную. В репозиторий коммитим `gradlew`, `gradlew.bat` и `gradle/wrapper/`.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Gradle собирает проект",
      "subtitle": "Окно Build показывает результат сборки и первую ошибку",
      "badge": "",
      "body": "- `build.gradle.kts` хранит SDK, плагины и зависимости\n- Gradle Sync загружает зависимости проекта\n- Если Sync завершился с ошибкой, сначала смотрим Build",
      "layout": "screenshot-demo",
      "image": "../../assets/ide/build-window.png",
      "imageKind": "screenshot",
      "imageAlt": "Окно Build с результатом сборки Gradle",
      "imageCaption": "",
      "notes": "«Failed to resolve» / proxy / DNS — частая боль в аудитории. Совет: дождаться Sync, читать первое красное сообщение, не десять подряд Rebuild.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Logcat — консоль приложения",
      "subtitle": "Здесь видны сообщения приложения и причина падения",
      "badge": "",
      "body": "- Сверху выбираем устройство, приложение и уровень логов\n- При падении здесь появляется stack trace\n- Сообщение из кода: `Log.d(\"MainActivity\", \"кнопка нажата\")`",
      "layout": "screenshot-demo",
      "image": "../../assets/ide/logcat.png",
      "imageKind": "screenshot",
      "imageAlt": "Окно Logcat в Android Studio",
      "imageCaption": "",
      "notes": "Показать фильтр по пакету. Тег — короткое имя класса. `println` тоже всплывёт, но в Android принято `Log.`*.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Кнопка Run — что происходит",
      "subtitle": "",
      "badge": "",
      "body": "1. Gradle собирает модуль `app`\n2. Упаковывается APK\n3. `adb` ставит пакет на выбранное устройство\n4. Система запускает launcher Activity\n5. Logcat начинает заполняться",
      "image": "../../assets/ide/run-toolbar.png",
      "imageKind": "screenshot",
      "imageAlt": "Выбор устройства и кнопка Run в панели Android Studio",
      "imageCaption": "На верхней панели: конфигурация app, целевое устройство и зелёная кнопка Run",
      "notes": "Если выбрано «No devices» — Run некуда ставить. Сначала Device Manager или USB. «Install failed» часто значит: старое приложение с другим ключом подписи — удалить с эмулятора и поставить снова.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "practice",
      "title": "Практика. Клонируем шаблон и запускаем",
      "subtitle": "",
      "badge": "Практика",
      "body": "1. Открыть [репозиторий FinanceApp](https://github.com/kolxz2/FinanceApp)\n2. `git clone https://github.com/kolxz2/FinanceApp.git`\n3. Открыть папку `FinanceApp` в Android Studio\n4. Дождаться Gradle Sync — подключится локальный `pre-push` hook\n5. Выбрать эмулятор / телефон и нажать Run ▶",
      "notes": "Ссылка на репозиторий есть прямо на слайде. После Gradle Sync проверить, что проект собирается и запускается.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Git",
      "subtitle": "История изменений проекта на вашем компьютере",
      "badge": "",
      "body": "- Рабочая папка, staging и commit\n- Отдельная ветка для каждой лекции\n- Слияние изменений через merge\n- Исключение служебных файлов через .gitignore",
      "outcome": "Сохраняете изменения понятными коммитами и работаете в отдельной ветке.",
      "notes": "Git — обязательный навык курса, не «дополнительная глава». Теория короткая, сразу в практику на своём проекте.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Git — машина времени для кода",
      "subtitle": "",
      "badge": "",
      "body": "- Хранит **историю изменений**, не только последнюю папку\n- Можно откатиться, сравнить, работать параллельно\n- Команда видит, кто что менял\n- Без Git: «у меня на флешке версия_финал_2_точно»\n- На курсе Git = способ сдачи и способ учиться как в индустрии",
      "image": "../../assets/concepts/linus-torvalds-nvidia.jpg",
      "imageAlt": "Линус Торвальдс во время выступления в 2012 году",
      "imageCaption": "Линус Торвальдс создал Linux и Git. Известный эпизод с NVIDIA, 2012 год",
      "notes": "Git ≠ GitHub. Git работает локально даже без интернета. GitHub — сайт, куда мы отправляем историю. Фото: https://www.newgadgets.de/43133/nvidia-linus-torvalds/ — эпизод с ответом Линуса Торвальдса компании NVIDIA в 2012 году.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Working directory → Staging → Commit → Push",
      "subtitle": "",
      "badge": "",
      "body": "1. Вы меняете файлы в рабочей папке\n2. `git add` отбирает изменения в staging\n3. `git commit` сохраняет локальный снимок\n4. `git push` отправляет новые коммиты на GitHub\n5. До push преподаватель и команда не видят ваши коммиты\n6. `git status` показывает состояние файлов и ветки",
      "notes": "Самая частая ошибка новичка: commit без add. Вторая: add всего подряд, включая `build/` и `.idea`. Для этого `.gitignore`.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Хороший commit",
      "subtitle": "",
      "badge": "",
      "body": "```\ngit add .\ngit commit -m \"Add Hello World screen\"\n```\n\n- Сообщение на английском или русском — но **по делу**\n- Один коммит = одно логическое изменение\n- Плохо: `git commit -m \"asdf\"` / `\"правки\"` / `\"всё\"`\n- Хорошо: `\"Add README with student name\"` / `\"Change greeting text\"`",
      "notes": "На курсе не требуем Conventional Commits в полном объёме. Требуем читаемость. Преподаватель читает `git log` при оценке.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Ветка — изолированная линия работы",
      "subtitle": "",
      "badge": "",
      "body": "- `master` — стабильная принятая версия\n- `homework/01-short-description` — работа над ДЗ №1\n- Перед началом: `git switch master` и `git pull`\n- Новая ветка: `git switch -c homework/01-short-description`\n- Домашнюю работу **нельзя** выполнять непосредственно в `master`",
      "image": "../../assets/concepts/git-branch.png",
      "imageKind": "visual",
      "imageAlt": "Ветка homework отделяется от стабильной линии master и возвращается в неё",
      "imageCaption": "Изменения в homework-ветке не затрагивают master до слияния Pull Request",
      "notes": "Примеры: homework/01-layout, homework/02-navigation, homework/03-database. Прямой push в master запрещён.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "merge и rebase — разные способы объединить историю",
      "subtitle": "",
      "badge": "",
      "body": "| | merge | rebase |\n| Что делает | Создаёт общий commit слияния | Переносит ваши commits на новую основу |\n| История | Сохраняет реальное ветвление | Получается ровная линия |\n| Хэши commits | Не меняются | Пересоздаются |\n| Когда применять | Pull Request и общие ветки | Обновление своей локальной ветки |\n| Главное правило | Безопасен для опубликованной истории | Не переписывать чужую или общую ветку |\n\nНа курсе используем **Merge Pull Request** после ревью.",
      "notes": "Rebase не склеивает готовые ветки тем же способом, что merge. Он переносит последовательность коммитов и меняет их хэши. Для первой лекции достаточно правила: общий PR вливаем merge, rebase используем только осознанно в своей ветке.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": ".gitignore — что не кладём в Git",
      "subtitle": "",
      "badge": "",
      "body": "Не коммитим:\n\n- `build/`, `.gradle/` — продукты сборки\n- локальный SDK path (`local.properties`)\n- кэш и крупные бинарники\n- ключи, пароли, `google-services.json` с секретами (позже)\n\nШаблон Android Studio уже содержит разумный `.gitignore` — не удаляйте его.",
      "notes": "`local.properties` содержит путь вида `C:\\Users\\...` — у преподавателя другой диск. Поэтому файл игнорируется. SDK у каждого свой.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "practice",
      "title": "Практика. Ветка для первой работы",
      "subtitle": "",
      "badge": "Практика",
      "body": "В папке `FinanceApp`:\n\n```\ngit switch master\ngit pull\ngit switch -c homework/01-first-pr\ngit branch --show-current\n```\n\nСделайте небольшое изменение по заданию семинара. `git init` не нужен: репозиторий уже клонирован.",
      "notes": "Убедиться, что команда показывает homework/01-first-pr. Уже сделанные локальные коммиты сохранятся и после создания новой ветки.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "GitHub",
      "subtitle": "Удалённая копия проекта и проверка изменений",
      "badge": "",
      "body": "- Отправка и получение коммитов\n- Pull Request как место проверки кода\n- Автоматические Detekt, тесты, Android Lint и сборка APK\n- Доступ преподавателя к репозиторию",
      "outcome": "Публикуете ветку на GitHub и открываете Pull Request.",
      "notes": "GitHub — место сдачи. Можно GitLab/Gitea в жизни; на курсе стандарт — GitHub.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Локальный Git и удалённый GitHub",
      "subtitle": "",
      "badge": "",
      "body": "- Исходный проект: [github.com/kolxz2/FinanceApp](https://github.com/kolxz2/FinanceApp)\n- После clone адрес уже сохранён под именем `origin`\n\n```\ngit remote -v\n```\n\n- Для своего репозитория добавьте преподавателя `kolxz2` в Settings → Collaborators\n- Пароли и токены преподавателю не передавайте",
      "notes": "Reviewer можно назначить только после предоставления доступа. Приглашение преподавателю достаточно отправить один раз.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "push отправляет, pull забирает",
      "subtitle": "",
      "badge": "",
      "body": "```\ngit add .\ngit commit -m \"Выполнена домашняя работа №1\"\ngit push -u origin homework/01-first-pr\n```\n\n- `-u` запоминает связь ветки с remote\n- После замечаний: новый commit и обычный `git push`\n- Pull Request обновится автоматически",
      "notes": "«У меня всё работает локально» — не сдача. Сдача = видно на GitHub. Если push отклонён: сначала pull, не force (force на курсе запрещён без отдельного разрешения).",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Pull Request — просьба влить ветку",
      "subtitle": "",
      "badge": "",
      "body": "- PR: «вот ветка `homework/01-first-pr`, влейте в `master`»\n- Заполните описание и список самопроверки\n- Добавьте `kolxz2` в **Reviewers**\n- Дождитесь проверки **Homework checks / Build, test and APK**\n- После замечаний не закрывайте PR: исправьте код и сделайте `git push` в ту же ветку",
      "notes": "PR — основной артефакт сдачи. Комментарий в Telegram «я сделал» без ссылки на PR не считается.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Результаты проверки и APK",
      "subtitle": "",
      "badge": "",
      "body": "- Статусы видны внизу Pull Request и во вкладке **Checks**\n- Бот оставляет комментарий по каждой проверке\n- При успехе появляется ссылка **Скачать APK**\n- APK и отчёты хранятся в запуске GitHub Actions 30 дней\n- Если проверка красная: открыть первый шаг с крестиком, прочитать журнал, исправить и сделать push в ту же ветку",
      "notes": "После принятия и merge Pull Request GitHub создаёт тег и Release с принятой версией APK.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "practice",
      "title": "Практика. Локальная проверка и push",
      "subtitle": "",
      "badge": "Практика",
      "body": "1. Запустить локально: `./gradlew detekt testDebugUnitTest lintDebug assembleDebug`\n2. Windows: `.\\gradlew.bat detekt testDebugUnitTest lintDebug assembleDebug`\n3. Исправить ошибки; отчёт Detekt: `app/build/reports/detekt/detekt.html`\n4. Выполнить `git add .` и commit\n5. Отправить ветку: `git push -u origin homework/01-first-pr`",
      "notes": "Detekt также запускается pre-push hook. Ошибки видны в Git → Console. Не обходить проверку: исправить первую реальную ошибку и повторить push.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Рабочий процесс курса",
      "subtitle": "Одинаковый цикл сдачи каждой домашней работы",
      "badge": "",
      "body": "- Обновить `master`\n- Создать ветку `homework/NN-short-description`\n- Проверить, сделать commit и push\n- Открыть Pull Request в `master` и назначить reviewer",
      "outcome": "Готовы повторять рабочий цикл курса без потери истории изменений.",
      "notes": "Этот слайд-процесс будут повторять 14 раз. Стоит задержаться и прогнать вслух.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Повторяйте это 15 раз",
      "subtitle": "",
      "badge": "",
      "body": "```\ngit switch master\ngit pull\ngit switch -c homework/NN-short-description\n# ... работа, проверка, коммиты ...\ngit push -u origin homework/NN-short-description\n# GitHub: Pull Request → master\n```\n\n- Одно ДЗ — одна ветка — один PR\n- После принятия GitHub создаст тег и Release с APK",
      "notes": "Исправления всегда отправляются в ту же ветку и тот же PR. Новый PR после замечаний создавать не надо.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "practice",
      "title": "Практика. Открываем первый Pull Request",
      "subtitle": "",
      "badge": "Практика",
      "body": "1. После push нажмите **Compare & pull request**\n2. Base: `master` ← compare: `homework/01-first-pr`\n3. Заполните описание и самопроверку\n4. Нажмите **Create pull request**\n5. В **Reviewers** выберите `kolxz2`\n6. Дождитесь зелёной проверки **Build, test and APK**",
      "notes": "Если kolxz2 не виден в Reviewers, сначала Settings → Access → Collaborators → Add people → kolxz2 и дождаться принятия приглашения.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Шаблон описания Pull Request",
      "subtitle": "",
      "badge": "",
      "body": "```\n## Что сделано\n- Открыт и запущен FinanceApp\n- Выполнено задание семинара\n\n## Самопроверка\n- [x] Detekt, тесты, Lint и assembleDebug проходят\n\n## Вопросы преподавателю\n- ...\n```\n\nПосле замечаний обновляйте этот PR обычным `git push`.",
      "notes": "Картинку можно перетащить в поле GitHub. Не присылать 200 МБ видео — 10–20 секунд или один кадр эмулятора.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "homework",
      "title": "Домашнее задание к лекции 1",
      "subtitle": "",
      "badge": "Домашнее задание",
      "body": "Обязательно:\n\n- [FinanceApp](https://github.com/kolxz2/FinanceApp) клонирован и запускается\n- Работа выполнена в ветке `homework/01-short-description`\n- Локальные проверки проходят\n- Открыт Pull Request в `master`\n- `kolxz2` назначен reviewer\n\nДедлайн: **7 дней**.",
      "notes": "Опциональный второй коммит учит: изменение → add → commit → push. Кто сделает — проще на лекции 2.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Если изменения не отправляются",
      "subtitle": "",
      "badge": "",
      "body": "- Сначала прочитайте ошибку в **Git → Console**\n- Если push в `master` запрещён: `git switch -c homework/01-short-description`\n- Если push остановил Detekt: откройте `app/build/reports/detekt/detekt.html`\n- Исправьте ошибки, затем снова `git add`, `git commit` и `git push`\n- Не используйте force push и не создавайте новый PR",
      "notes": "Создание ветки после локального коммита не удаляет сделанную работу: коммиты останутся в новой ветке.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "На чём обычно спотыкаются",
      "subtitle": "",
      "badge": "",
      "body": "- Работа или push выполняются прямо в `master`\n- Ветка названа `dz` вместо `homework/01-short-description`\n- Локальные проверки не запускались\n- После замечаний создан новый PR вместо обновления старого\n- Преподавателю не выдан доступ и reviewer не назначен\n- Красная проверка оставлена без просмотра журнала",
      "notes": "Пройти список как предполётный чеклист перед тем, как студенты разойдутся.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Перед тем как закрыть ноутбук",
      "subtitle": "",
      "badge": "",
      "body": "- [ ] Текущая ветка начинается с `homework/01-`\n- [ ] `git status` — чисто\n- [ ] Detekt, тесты, Lint и debug-сборка проходят\n- [ ] Открыт PR в `master`\n- [ ] `kolxz2` добавлен в Reviewers\n- [ ] Проверка **Build, test and APK** завершилась успешно",
      "notes": "Попросить 2–3 человек кинуть ссылку на репозиторий в чат курса — живая проверка, что доступ не «только мне».",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Лекция 2 — Kotlin: основы языка",
      "subtitle": "",
      "badge": "",
      "body": "- Зачем Kotlin в Android\n- `val` / `var`, типы, null safety\n- Функции, `if` / `when`, циклы\n- Практика без UI: scratch / консоль / Log\n- ДЗ: задачи в пакете `kotlin.basics`, PR `lecture-02`\n\nСегодняшний Git-процесс на лекции 2 уже считается известным.",
      "notes": "Кто не поставил Studio сегодня — обязан сделать до лекции 2, иначе не напишет даже scratch. Язык пойдёт быстро.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "content",
      "title": "Что забрать с собой",
      "subtitle": "",
      "badge": "",
      "body": "1. Android-приложение = APK + манифест + компоненты; вам пока важен Activity\n2. Kotlin живёт на JVM-стеке, на устройстве исполняет ART\n3. Studio + SDK + эмулятор (или телефон) — рабочее место\n4. Gradle собирает, Logcat показывает, Run ставит пакет\n5. GitHub — сдача: `homework/...` → PR в `master` → проверки → ревью\n6. Практика: клонировать FinanceApp и открыть первый Pull Request",
      "notes": "Повторить вслух за 60 секунд. Вопросы — следующий слайд.",
      "kicker": "",
      "photo": false
    },
    {
      "type": "section",
      "title": "Вопросы",
      "subtitle": "Проверяем готовность к следующей лекции",
      "badge": "",
      "body": "- Не работает эмулятор?\n- `git push` отвергает?\n- Не видно репозитория у преподавателя?\n\nОстаёмся после пары на 10 минут к установке.",
      "outcome": "Android Studio запускает проект, а репозиторий и Pull Request доступны преподавателю.",
      "notes": "Собрать тех, у кого красный Gradle или нет GitHub. Не разбирать индивидуальный BIOS на всю аудиторию. Напомнить дедлайн: 7 дней, 4 балла, без Git ДЗ не существует. Если останется минута — ещё раз: вопросы можно в PR и в чат курса.",
      "kicker": "",
      "photo": false
    }
  ]
};
